export * from './add-exam/add-exam.component'
export * from './add-question/add-question.component'
export * from './list-exams/list-exams.component'
export * from './edit-exams/edit-exams.component'
export * from './list-questions/list-questions.component'
export * from './update-exam/update-exam.component'
export * from './exam-results/exam-results.component'
export * from './select-random-questions-by-tag/select-random-questions-by-tag.component'
